/*
 * system.h
 *
 *  Created on: 22 Sep 2015
 *      Author: ab495
 */

#ifndef SYSTEM_H_
#define SYSTEM_H_

#define ALT_LWFPGA_BASE         	 0xFF200000
#define ALT_LWFPGA_SYSID_OFFSET 	 0x00010000
#define ALT_LWFPGA_LED_OFFSET   	 0x000000D0
#define ALT_LWFPGA_SWITCH_OFFSET	 0x000000C0
#define ALT_LWFPGA_KEY_OFFSET		 0x000000B0
#define ALT_LWFPGA_HEXA_OFFSET		 0x000000A0
#define ALT_LWFPGA_HEXB_OFFSET		 0x00000090
#define ALT_LWFPGA_GPIO_0A_OFFSET	 0x00000060
#define ALT_LWFPGA_GPIO_0B_OFFSET	 0x00000040
#define ALT_LWFPGA_GPIO_1A_OFFSET	 0x00000020
#define ALT_LWFPGA_GPIO_1B_OFFSET	 0x00000000
#define ALT_LWFPGA_COUNTER_OFFSET	 0x00000080

#define ALT_LWFPGA_SYSID_BASE      ( ALT_LWFPGA_BASE + ALT_LWFPGA_SYSID_OFFSET )
#define ALT_LWFPGA_LED_BASE        ( ALT_LWFPGA_BASE + ALT_LWFPGA_LED_OFFSET )
#define ALT_LWFPGA_SWITCH_BASE     ( ALT_LWFPGA_BASE + ALT_LWFPGA_SWITCH_OFFSET )
#define ALT_LWFPGA_KEY_BASE        ( ALT_LWFPGA_BASE + ALT_LWFPGA_KEY_OFFSET )
#define ALT_LWFPGA_HEXA_BASE       ( ALT_LWFPGA_BASE + ALT_LWFPGA_HEXA_OFFSET )
#define ALT_LWFPGA_HEXB_BASE       ( ALT_LWFPGA_BASE + ALT_LWFPGA_HEXB_OFFSET )
#define ALT_LWFPGA_GPIO_0A_BASE    ( ALT_LWFPGA_BASE + ALT_LWFPGA_GPIO_0A_OFFSET )
#define ALT_LWFPGA_GPIO_0B_BASE    ( ALT_LWFPGA_BASE + ALT_LWFPGA_GPIO_0B_OFFSET )
#define ALT_LWFPGA_GPIO_1A_BASE    ( ALT_LWFPGA_BASE + ALT_LWFPGA_GPIO_1A_OFFSET )
#define ALT_LWFPGA_GPIO_1B_BASE    ( ALT_LWFPGA_BASE + ALT_LWFPGA_GPIO_1B_OFFSET )
#define ALT_LWFPGA_COUNTER_BASE    ( ALT_LWFPGA_BASE + ALT_LWFPGA_COUNTER_OFFSET )

#endif /* SYSTEM_H_ */
